import React from "react";

import {
    AccountBookFilled,
    AlignLeftOutlined,
    AccountBookOutlined,
    AccountBookTwoTone,
    AlertFilled,
    AlertOutlined,
    AlertTwoTone,
    AlibabaOutlined,
    AliwangwangFilled,
    AliwangwangOutlined,
    AliyunOutlined,
    ShoppingOutlined,
    AmazonCircleFilled,
    AmazonOutlined,
    AmazonSquareFilled,
    AndroidFilled,
    AndroidOutlined,
    AntCloudOutlined,
    AntDesignOutlined,
    ApartmentOutlined,
    ApiFilled,
    ApiOutlined,
    ApiTwoTone,
    AppleFilled,
    AppleOutlined,
    AppstoreAddOutlined,
    AppstoreFilled,
    AppstoreOutlined,
    AppstoreTwoTone,
    AreaChartOutlined,
    ArrowDownOutlined,
    ArrowLeftOutlined,
    ArrowRightOutlined,
    ArrowUpOutlined,
    ArrowsAltOutlined,
    AudioFilled,
    AudioOutlined,
    AudioMutedOutlined,
    AuditOutlined,
    ShoppingTwoTone,
    BackwardFilled,
    BackwardOutlined,
    BankFilled,
    BankOutlined,
    BankTwoTone,
    BarChartOutlined,
    BarcodeOutlined,
    BarsOutlined,
    BorderBottomOutlined,
    BehanceCircleFilled,
    BehanceOutlined,
    BehanceSquareFilled,
    BellFilled,
    BellOutlined,
    BellTwoTone,
    BgColorsOutlined,
    BlockOutlined,
    BoldOutlined,
    BookFilled,
    BookOutlined,
    BookTwoTone,
    BorderHorizontalOutlined,
    BorderInnerOutlined,
    BorderLeftOutlined,
    BorderOuterOutlined,
    BorderOutlined,
    ShoppingFilled,
    BorderRightOutlined,
    BorderTopOutlined,
    BorderVerticleOutlined,
    BoxPlotFilled,
    BoxPlotOutlined,
    BoxPlotTwoTone,
    BranchesOutlined,
    BugFilled,
    BugOutlined,
    BugTwoTone,
    BuildFilled,
    BuildOutlined,
    BuildTwoTone,
    BulbFilled,
    BulbOutlined,
    BulbTwoTone,
    CalculatorFilled,
    CalculatorOutlined,
    CalculatorTwoTone,
    CalendarFilled,
    CalendarOutlined,
    CalendarTwoTone,
    CameraFilled,
    CameraOutlined,
    CameraTwoTone,
    CarFilled,
    CarOutlined,
    CarTwoTone,
    CaretDownFilled,
    CaretDownOutlined,
    CaretLeftFilled,
    CaretLeftOutlined,
    CaretRightFilled,
    CaretRightOutlined,
    CaretUpFilled,
    CaretUpOutlined,
    CarryOutFilled,
    CarryOutOutlined,
    CarryOutTwoTone,
    CheckCircleFilled,
    CheckCircleOutlined,
    CheckCircleTwoTone,
    CheckOutlined,
    CheckSquareFilled,
    CheckSquareOutlined,
    CheckSquareTwoTone,
    ChromeFilled,
    ChromeOutlined,
    CiCircleFilled,
    CiCircleOutlined,
    CiCircleTwoTone,
    CiOutlined,
    CiTwoTone,
    ClearOutlined,
    ClockCircleFilled,
    ClockCircleOutlined,
    ClockCircleTwoTone,
    CloseCircleFilled,
    CloseCircleOutlined,
    CloseCircleTwoTone,
    CloseOutlined,
    CloseSquareFilled,
    CloseSquareOutlined,
    CloseSquareTwoTone,
    CloudDownloadOutlined,
    CloudFilled,
    CloudOutlined,
    CloudServerOutlined,
    CloudSyncOutlined,
    CloudTwoTone,
    CloudUploadOutlined,
    ClusterOutlined,
    CodeFilled,
    CodeOutlined,
    CodeSandboxCircleFilled,
    CodeSandboxOutlined,
    CodeSandboxSquareFilled,
    CodeTwoTone,
    CodepenCircleFilled,
    CodepenCircleOutlined,
    CodepenOutlined,
    CodepenSquareFilled,
    CoffeeOutlined,
    ColumnHeightOutlined,
    ColumnWidthOutlined,
    CommentOutlined,
    CompassFilled,
    CompassOutlined,
    CompassTwoTone,
    CompressOutlined,
    ConsoleSqlOutlined,
    ContactsFilled,
    ContactsOutlined,
    ContactsTwoTone,
    ContainerFilled,
    ContainerOutlined,
    ContainerTwoTone,
    ControlFilled,
    ControlOutlined,
    ControlTwoTone,
    CopyFilled,
    CopyOutlined,
    CopyTwoTone,
    CreditCardFilled,
    CreditCardOutlined,
    CreditCardTwoTone,
    CrownFilled,
    CrownOutlined,
    CrownTwoTone,
    CustomerServiceFilled,
    CustomerServiceOutlined,
    CustomerServiceTwoTone,
    DashOutlined,
    DashboardFilled,
    DashboardOutlined,
    DashboardTwoTone,
    DatabaseFilled,
    DatabaseOutlined,
    DatabaseTwoTone,
    DeleteColumnOutlined,
    DeleteFilled,
    DeleteOutlined,
    DeleteRowOutlined,
    DeleteTwoTone,
    DeliveredProcedureOutlined,
    DeploymentUnitOutlined,
    DesktopOutlined,
    DiffFilled,
    DiffOutlined,
    DiffTwoTone,
    DingdingOutlined,
    DingtalkCircleFilled,
    DingtalkOutlined,
    DingtalkSquareFilled,
    DisconnectOutlined,
    DislikeFilled,
    DislikeOutlined,
    DislikeTwoTone,
    DollarCircleFilled,
    DollarCircleOutlined,
    DollarCircleTwoTone,
    DollarOutlined,
    DollarTwoTone,
    DotChartOutlined,
    DoubleLeftOutlined,
    DoubleRightOutlined,
    DownCircleFilled,
    DownCircleOutlined,
    DownCircleTwoTone,
    DownOutlined,
    DownSquareFilled,
    DownSquareOutlined,
    DownSquareTwoTone,
    DownloadOutlined,
    DragOutlined,
    DribbbleCircleFilled,
    DribbbleOutlined,
    DribbbleSquareFilled,
    DribbbleSquareOutlined,
    DropboxCircleFilled,
    DropboxOutlined,
    DropboxSquareFilled,
    EditFilled,
    EditOutlined,
    EditTwoTone,
    EllipsisOutlined,
    EnterOutlined,
    EnvironmentFilled,
    EnvironmentOutlined,
    EnvironmentTwoTone,
    EuroCircleFilled,
    EuroCircleOutlined,
    EuroCircleTwoTone,
    EuroOutlined,
    EuroTwoTone,
    ExceptionOutlined,
    ExclamationCircleFilled,
    ExclamationCircleOutlined,
    ExclamationCircleTwoTone,
    ExclamationOutlined,
    ExpandAltOutlined,
    ExpandOutlined,
    FormOutlined,
    ExperimentFilled,
    ExperimentOutlined,
    ExperimentTwoTone,
    ExportOutlined,
    EyeFilled,
    EyeInvisibleFilled,
    EyeInvisibleOutlined,
    EyeInvisibleTwoTone,
    EyeOutlined,
    EyeTwoTone,
    FacebookFilled,
    FacebookOutlined,
    FallOutlined,
    FastBackwardFilled,
    FastBackwardOutlined,
    FastForwardFilled,
    FastForwardOutlined,
    FieldBinaryOutlined,
    FieldNumberOutlined,
    FieldStringOutlined,
    FieldTimeOutlined,
    FileAddFilled,
    FileAddOutlined,
    FileAddTwoTone,
    FileDoneOutlined,
    FileExcelFilled,
    FileExcelOutlined,
    FileExcelTwoTone,
    FileExclamationFilled,
    FileExclamationOutlined,
    FileExclamationTwoTone,
    FileFilled,
    FileGifOutlined,
    FileImageFilled,
    FileImageOutlined,
    FileImageTwoTone,
    FileJpgOutlined,
    FileMarkdownFilled,
    FileMarkdownOutlined,
    FileMarkdownTwoTone,
    FileOutlined,
    FilePdfFilled,
    FilePdfOutlined,
    FilePdfTwoTone,
    FilePptFilled,
    FilePptOutlined,
    FilePptTwoTone,
    FileProtectOutlined,
    FileSearchOutlined,
    FileSyncOutlined,
    FileTextFilled,
    FileTextOutlined,
    FileTextTwoTone,
    FileTwoTone,
    FileUnknownFilled,
    FileUnknownOutlined,
    FileUnknownTwoTone,
    FileWordFilled,
    FileWordOutlined,
    FileWordTwoTone,
    FileZipFilled,
    FileZipOutlined,
    FileZipTwoTone,
    FilterFilled,
    FilterOutlined,
    FilterTwoTone,
    FireFilled,
    FireOutlined,
    FireTwoTone,
    FlagFilled,
    FlagOutlined,
    FlagTwoTone,
    FolderAddFilled,
    FolderAddOutlined,
    FolderAddTwoTone,
    FolderFilled,
    FolderOpenFilled,
    FolderOpenOutlined,
    FolderOpenTwoTone,
    FolderOutlined,
    FolderTwoTone,
    FolderViewOutlined,
    FontColorsOutlined,
    FontSizeOutlined,
    ForkOutlined,
    FormatPainterFilled,
    FormatPainterOutlined,
    ForwardFilled,
    ForwardOutlined,
    FrownFilled,
    FrownOutlined,
    FrownTwoTone,
    FullscreenExitOutlined,
    FullscreenOutlined,
    FunctionOutlined,
    FundFilled,
    FundOutlined,
    FundProjectionScreenOutlined,
    FundTwoTone,
    FundViewOutlined,
    FunnelPlotFilled,
    FunnelPlotOutlined,
    FunnelPlotTwoTone,
    GatewayOutlined,
    GifOutlined,
    GiftFilled,
    GiftOutlined,
    GiftTwoTone,
    GithubFilled,
    GithubOutlined,
    GitlabFilled,
    GitlabOutlined,
    GlobalOutlined,
    GoldFilled,
    GoldOutlined,
    GoldTwoTone,
    GoldenFilled,
    GoogleCircleFilled,
    GoogleOutlined,
    GooglePlusCircleFilled,
    GooglePlusOutlined,
    GooglePlusSquareFilled,
    GoogleSquareFilled,
    GroupOutlined,
    HddFilled,
    HddOutlined,
    HddTwoTone,
    HeartFilled,
    HeartOutlined,
    HeartTwoTone,
    HeatMapOutlined,
    HighlightFilled,
    HighlightOutlined,
    HighlightTwoTone,
    HistoryOutlined,
    HomeFilled,
    HomeOutlined,
    HomeTwoTone,
    HourglassFilled,
    HourglassOutlined,
    HourglassTwoTone,
    Html5Filled,
    Html5Outlined,
    Html5TwoTone,
    IdcardFilled,
    IdcardOutlined,
    IdcardTwoTone,
    IeCircleFilled,
    IeOutlined,
    IeSquareFilled,
    ImportOutlined,
    InboxOutlined,
    InfoCircleFilled,
    InfoCircleOutlined,
    InfoCircleTwoTone,
    InfoOutlined,
    InsertRowAboveOutlined,
    InsertRowBelowOutlined,
    InsertRowLeftOutlined,
    InsertRowRightOutlined,
    InstagramFilled,
    InstagramOutlined,
    InsuranceFilled,
    InsuranceOutlined,
    InsuranceTwoTone,
    InteractionFilled,
    InteractionOutlined,
    InteractionTwoTone,
    IssuesCloseOutlined,
    ItalicOutlined,
    KeyOutlined,
    LaptopOutlined,
    LayoutFilled,
    LayoutOutlined,
    LayoutTwoTone,
    LeftCircleFilled,
    LeftCircleOutlined,
    LeftCircleTwoTone,
    LeftOutlined,
    LeftSquareFilled,
    LeftSquareOutlined,
    LeftSquareTwoTone,
    LikeFilled,
    LikeOutlined,
    LikeTwoTone,
    LineChartOutlined,
    LineHeightOutlined,
    LineOutlined,
    LinkOutlined,
    LinkedinFilled,
    LinkedinOutlined,
    Loading3QuartersOutlined,
    LoadingOutlined,
    LockFilled,
    LockOutlined,
    LockTwoTone,
    LoginOutlined,
    LogoutOutlined,
    MacCommandFilled,
    MacCommandOutlined,
    MailFilled,
    MailOutlined,
    MailTwoTone,
    ManOutlined,
    MedicineBoxFilled,
    MedicineBoxOutlined,
    MedicineBoxTwoTone,
    MediumCircleFilled,
    MediumOutlined,
    MediumSquareFilled,
    MediumWorkmarkOutlined,
    MehFilled,
    MehOutlined,
    MehTwoTone,
    MenuFoldOutlined,
    MenuOutlined,
    MenuUnfoldOutlined,
    MergeCellsOutlined,
    MessageFilled,
    MessageOutlined,
    MessageTwoTone,
    MinusCircleFilled,
    MinusCircleOutlined,
    MinusCircleTwoTone,
    MinusOutlined,
    MinusSquareFilled,
    MinusSquareOutlined,
    MinusSquareTwoTone,
    MobileFilled,
    MobileOutlined,
    MobileTwoTone,
    MoneyCollectFilled,
    MoneyCollectOutlined,
    MoneyCollectTwoTone,
    MonitorOutlined,
    MoreOutlined,
    NodeCollapseOutlined,
    NodeExpandOutlined,
    NodeIndexOutlined,
    NotificationFilled,
    NotificationOutlined,
    NotificationTwoTone,
    NumberOutlined,
    OneToOneOutlined,
    OrderedListOutlined,
    PaperClipOutlined,
    PartitionOutlined,
    PauseCircleFilled,
    PauseCircleOutlined,
    PauseCircleTwoTone,
    PauseOutlined,
    PayCircleFilled,
    PayCircleOutlined,
    PercentageOutlined,
    PhoneFilled,
    PhoneOutlined,
    PhoneTwoTone,
    PicCenterOutlined,
    PicLeftOutlined,
    PicRightOutlined,
    PictureFilled,
    PictureOutlined,
    PictureTwoTone,
    PieChartFilled,
    PieChartOutlined,
    PieChartTwoTone,
    PlayCircleFilled,
    PlayCircleOutlined,
    PlayCircleTwoTone,
    PlaySquareFilled,
    PlaySquareOutlined,
    PlaySquareTwoTone,
    PlusCircleFilled,
    PlusCircleOutlined,
    PlusCircleTwoTone,
    PlusOutlined,
    PlusSquareFilled,
    PlusSquareOutlined,
    PlusSquareTwoTone,
    PoundCircleFilled,
    PoundCircleOutlined,
    PoundCircleTwoTone,
    PoundOutlined,
    PoweroffOutlined,
    PrinterFilled,
    PrinterOutlined,
    PrinterTwoTone,
    ProfileFilled,
    ProfileOutlined,
    ProfileTwoTone,
    ProjectFilled,
    ProjectOutlined,
    ProjectTwoTone,
    PropertySafetyFilled,
    PropertySafetyOutlined,
    PropertySafetyTwoTone,
    PullRequestOutlined,
    PushpinFilled,
    PushpinOutlined,
    PushpinTwoTone,
    QqCircleFilled,
    QqOutlined,
    QqSquareFilled,
    QrcodeOutlined,
    QuestionCircleFilled,
    QuestionCircleOutlined,
    QuestionCircleTwoTone,
    QuestionOutlined,
    RadarChartOutlined,
    RadiusBottomleftOutlined,
    RadiusBottomrightOutlined,
    RadiusSettingOutlined,
    RadiusUpleftOutlined,
    RadiusUprightOutlined,
    ReadFilled,
    ReadOutlined,
    ReconciliationFilled,
    ReconciliationOutlined,
    ReconciliationTwoTone,
    RedEnvelopeFilled,
    RedEnvelopeOutlined,
    RedEnvelopeTwoTone,
    RedditCircleFilled,
    RedditOutlined,
    RedditSquareFilled,
    RedoOutlined,
    ReloadOutlined,
    RestFilled,
    RestOutlined,
    RestTwoTone,
    RetweetOutlined,
    RightCircleFilled,
    RightCircleOutlined,
    RightCircleTwoTone,
    RightOutlined,
    RightSquareFilled,
    RightSquareOutlined,
    RightSquareTwoTone,
    RiseOutlined,
    RobotFilled,
    RobotOutlined,
    RocketFilled,
    RocketOutlined,
    RocketTwoTone,
    RollbackOutlined,
    RotateLeftOutlined,
    RotateRightOutlined,
    SafetyCertificateFilled,
    SafetyCertificateOutlined,
    SafetyCertificateTwoTone,
    SafetyOutlined,
    SaveFilled,
    SaveOutlined,
    SaveTwoTone,
    ScanOutlined,
    ScheduleFilled,
    ScheduleOutlined,
    ScheduleTwoTone,
    ScissorOutlined,
    SearchOutlined,
    SecurityScanFilled,
    SecurityScanOutlined,
    SecurityScanTwoTone,
    SelectOutlined,
    SendOutlined,
    SettingFilled,
    SettingOutlined,
    SettingTwoTone,
    ShakeOutlined,
    ShareAltOutlined,
    ShopFilled,
    ShopOutlined,
    ShopTwoTone,
    ShoppingCartOutlined,
    ShrinkOutlined,
    SignalFilled,
    SisternodeOutlined,
    SketchCircleFilled,
    SketchOutlined,
    SketchSquareFilled,
    SkinFilled,
    SkinOutlined,
    SkinTwoTone,
    SkypeFilled,
    SkypeOutlined,
    SlackCircleFilled,
    SlackOutlined,
    SlackSquareFilled,
    SlackSquareOutlined,
    SlidersFilled,
    SlidersOutlined,
    SlidersTwoTone,
    SmallDashOutlined,
    SmileFilled,
    SmileOutlined,
    SmileTwoTone,
    SnippetsFilled,
    SnippetsOutlined,
    SnippetsTwoTone,
    SolutionOutlined,
    SortAscendingOutlined,
    SortDescendingOutlined,
    SoundFilled,
    SoundOutlined,
    SoundTwoTone,
    SplitCellsOutlined,
    StarFilled,
    StarOutlined,
    StarTwoTone,
    StepBackwardFilled,
    StepBackwardOutlined,
    StepForwardFilled,
    StepForwardOutlined,
    StockOutlined,
    StopFilled,
    StopOutlined,
    StopTwoTone,
    StrikethroughOutlined,
    SubnodeOutlined,
    SwapLeftOutlined,
    SwapOutlined,
    SwapRightOutlined,
    SwitcherFilled,
    SwitcherOutlined,
    SwitcherTwoTone,
    SyncOutlined,
    TableOutlined,
    TabletFilled,
    TabletOutlined,
    TabletTwoTone,
    TagFilled,
    TagOutlined,
    TagTwoTone,
    TagsFilled,
    TagsOutlined,
    TagsTwoTone,
    TaobaoCircleFilled,
    TaobaoCircleOutlined,
    TaobaoOutlined,
    TaobaoSquareFilled,
    TeamOutlined,
    ThunderboltFilled,
    ThunderboltOutlined,
    ThunderboltTwoTone,
    ToTopOutlined,
    ToolFilled,
    ToolOutlined,
    ToolTwoTone,
    TrademarkCircleFilled,
    TrademarkCircleOutlined,
    TrademarkCircleTwoTone,
    TrademarkOutlined,
    TransactionOutlined,
    TranslationOutlined,
    TrophyFilled,
    TrophyOutlined,
    BehanceSquareOutlined,
    TrophyTwoTone,
    TwitterCircleFilled,
    TwitterOutlined,
    TwitterSquareFilled,
    UnderlineOutlined,
    UndoOutlined,
    UngroupOutlined,
    UnlockFilled,
    UnlockOutlined,
    UnlockTwoTone,
    UnorderedListOutlined,
    UpCircleFilled,
    UpCircleOutlined,
    UpCircleTwoTone,
    UpOutlined,
    UpSquareFilled,
    UpSquareOutlined,
    UpSquareTwoTone,
    UploadOutlined,
    UsbFilled,
    UsbOutlined,
    UsbTwoTone,
    UserAddOutlined,
    UserDeleteOutlined,
    UserOutlined,
    UserSwitchOutlined,
    UsergroupAddOutlined,
    UsergroupDeleteOutlined,
    VerifiedOutlined,
    VerticalAlignBottomOutlined,
    VerticalAlignMiddleOutlined,
    VerticalAlignTopOutlined,
    VerticalLeftOutlined,
    VerticalRightOutlined,
    VideoCameraAddOutlined,
    VideoCameraFilled,
    VideoCameraOutlined,
    VideoCameraTwoTone,
    WalletFilled,
    WalletOutlined,
    WalletTwoTone,
    WarningFilled,
    WarningOutlined,
    BorderlessTableOutlined,
    WarningTwoTone,
    WechatFilled,
    WechatOutlined,
    WeiboCircleFilled,
    WeiboCircleOutlined,
    WeiboOutlined,
    WeiboSquareFilled,
    WhatsAppOutlined,
    WifiOutlined,
    WindowsFilled,
    WindowsOutlined,
    WomanOutlined,
    YahooFilled,
    YahooOutlined,
    YoutubeFilled,
    YoutubeOutlined,
    YuqueFilled,
    YuqueOutlined,
    ZhihuCircleFilled,
    ZhihuOutlined,
    ZhihuSquareFilled,
    AudioTwoTone,
    AlipayCircleFilled,
    AlipayOutlined,
    AlipaySquareFilled,
    AlipayCircleOutlined,

  } from "@ant-design/icons";
  


export const IconsWindow = () => {

    const Icons = [
        { id: 1, icon: AccountBookFilled },
        { id: 2, icon: AccountBookOutlined },
        { id: 3, icon: AccountBookTwoTone },
        { id: 4, icon: ApiOutlined },
        { id: 5, icon: AlertFilled },
        { id: 6, icon: AlertOutlined },
        { id: 7, icon: AlertTwoTone },
        { id: 8, icon: AlibabaOutlined },
        { id: 9, icon: PicCenterOutlined },
        { id: 10, icon: AlignLeftOutlined },
        // { id: 11, icon: AlignRightOutlined },
        { id: 12, icon: AlipayCircleFilled },
        { id: 13, icon: AlipayCircleOutlined },
        { id: 14, icon: AlipayOutlined },
        { id: 15, icon: AlipaySquareFilled },
        { id: 16, icon: AliwangwangFilled },
        { id: 17, icon: AliwangwangOutlined },
        { id: 18, icon: AliyunOutlined },
        { id: 19, icon: AmazonCircleFilled },
        { id: 20, icon: AmazonOutlined },
        { id: 21, icon: AmazonSquareFilled },
        { id: 22, icon: AndroidFilled },
        { id: 23, icon: AndroidOutlined },
        { id: 24, icon: AntCloudOutlined },
        { id: 25, icon: AntDesignOutlined },
        { id: 26, icon: ApartmentOutlined },
        { id: 27, icon: ApiFilled },
        { id: 28, icon: ApiOutlined },
        { id: 29, icon: ApiTwoTone },
        { id: 30, icon: AppleFilled },
        { id: 31, icon: AppleOutlined },
        { id: 32, icon: AppstoreAddOutlined },
        { id: 33, icon: AppstoreFilled },
        { id: 34, icon: AppstoreOutlined },
        { id: 35, icon: AppstoreTwoTone },
        { id: 36, icon: AreaChartOutlined },
        { id: 37, icon: ArrowDownOutlined },
        { id: 38, icon: ArrowLeftOutlined },
        { id: 39, icon: ArrowRightOutlined },
        { id: 40, icon: ArrowUpOutlined },
        { id: 41, icon: ArrowsAltOutlined },
        { id: 42, icon: AudioFilled },
        { id: 43, icon: AudioMutedOutlined },
        { id: 44, icon: AudioOutlined },
        { id: 45, icon: AudioTwoTone },
        { id: 46, icon: AuditOutlined },
        { id: 47, icon: BackwardFilled },
        { id: 48, icon: BackwardOutlined },
        { id: 49, icon: BankFilled },
        { id: 50, icon: BankOutlined },
        { id: 51, icon: BankTwoTone },
        { id: 52, icon: BarChartOutlined },
        { id: 53, icon: BarcodeOutlined },
        { id: 54, icon: BarsOutlined },
        { id: 55, icon: BehanceCircleFilled },
        { id: 56, icon: BehanceOutlined },
        { id: 57, icon: BehanceSquareFilled },
        { id: 58, icon: BehanceSquareOutlined },
        { id: 59, icon: BellFilled },
        { id: 60, icon: BellOutlined },
        { id: 61, icon: BellTwoTone },
        { id: 62, icon: BgColorsOutlined },
        { id: 63, icon: BlockOutlined },
        { id: 64, icon: BoldOutlined },
        { id: 65, icon: BookFilled },
        { id: 66, icon: BookOutlined },
        { id: 67, icon: BookTwoTone },
        { id: 68, icon: BorderBottomOutlined },
        { id: 69, icon: BorderHorizontalOutlined },
        { id: 70, icon: BorderInnerOutlined },
        { id: 71, icon: BorderLeftOutlined },
        { id: 72, icon: BorderOuterOutlined },
        { id: 73, icon: BorderOutlined },
        { id: 74, icon: BorderRightOutlined },
        { id: 75, icon: BorderTopOutlined },
        { id: 76, icon: BorderVerticleOutlined },
        { id: 77, icon: BorderlessTableOutlined },
        { id: 78, icon: BoxPlotFilled },
        { id: 79, icon: BoxPlotOutlined },
        { id: 80, icon: BoxPlotTwoTone },
        { id: 81, icon: BranchesOutlined },
        { id: 82, icon: BugFilled },
        { id: 83, icon: BugOutlined },
        { id: 84, icon: BugTwoTone },
        { id: 85, icon: BuildFilled },
        { id: 86, icon: BuildOutlined },
        { id: 87, icon: BuildTwoTone },
        { id: 88, icon: BulbFilled },
        { id: 89, icon: BulbOutlined },
        { id: 90, icon: BulbTwoTone },
        { id: 91, icon: CalculatorFilled },
        { id: 92, icon: CalculatorOutlined },
        { id: 93, icon: CalculatorTwoTone },
        { id: 94, icon: CalendarFilled },
        { id: 95, icon: CalendarOutlined },
        { id: 96, icon: CalendarTwoTone },
        { id: 97, icon: CameraFilled },
        { id: 98, icon: CameraOutlined },
        { id: 99, icon: CameraTwoTone },
        { id: 100, icon: CarFilled },
        { id: 101, icon: CarOutlined },
        { id: 102, icon: CarTwoTone },
        { id: 103, icon: CarryOutFilled },
        { id: 104, icon: CarryOutOutlined },
        { id: 105, icon: CarryOutTwoTone },
        { id: 106, icon: CheckCircleFilled },
        { id: 107, icon: CheckCircleOutlined },
        { id: 108, icon: CheckCircleTwoTone },
        { id: 109, icon: CheckOutlined },
        { id: 110, icon: CheckSquareFilled },
        { id: 111, icon: CheckSquareOutlined },
        { id: 112, icon: CheckSquareTwoTone },
        { id: 113, icon: ChromeFilled },
        { id: 114, icon: ChromeOutlined },
        { id: 115, icon: CiCircleFilled },
        { id: 116, icon: CiCircleOutlined },
        { id: 117, icon: CiCircleTwoTone },
        { id: 118, icon: CiOutlined },
        { id: 119, icon: CiTwoTone },
        { id: 120, icon: ClearOutlined },
        { id: 121, icon: ClockCircleFilled },
        { id: 122, icon: ClockCircleOutlined },
        { id: 123, icon: ClockCircleTwoTone },
        { id: 124, icon: CloseCircleFilled },
        { id: 125, icon: CloseCircleOutlined },
        { id: 126, icon: CloseCircleTwoTone },
        { id: 127, icon: CloseOutlined },
        { id: 128, icon: CloseSquareFilled },
        { id: 129, icon: CloseSquareOutlined },
        { id: 130, icon: CloseSquareTwoTone },
        { id: 131, icon: CloudDownloadOutlined },
        { id: 132, icon: CloudFilled },
        { id: 133, icon: CloudOutlined },
        { id: 134, icon: CloudServerOutlined },
        { id: 135, icon: CloudSyncOutlined },
        { id: 136, icon: CloudTwoTone },
        { id: 137, icon: CloudUploadOutlined },
        { id: 138, icon: ClusterOutlined },
        { id: 139, icon: CodeFilled },
        { id: 140, icon: CodeOutlined },
        { id: 141, icon: CodeSandboxCircleFilled },
        { id: 142, icon: CodeSandboxOutlined },
        { id: 143, icon: CodeSandboxSquareFilled },
        { id: 144, icon: CodeTwoTone },
        { id: 145, icon: CodepenCircleFilled },
        { id: 146, icon: CodepenCircleOutlined },
        { id: 147, icon: CodepenOutlined },
        { id: 148, icon: CodepenSquareFilled },
        { id: 149, icon: CoffeeOutlined },
        { id: 150, icon: ColumnHeightOutlined },
        { id: 151, icon: ColumnWidthOutlined },
        { id: 152, icon: CommentOutlined },
        { id: 153, icon: CompassFilled },
        { id: 154, icon: CompassOutlined },
        { id: 155, icon: CompassTwoTone },
        { id: 156, icon: CompressOutlined },
        { id: 157, icon: ConsoleSqlOutlined },
        { id: 158, icon: ContactsFilled },
        { id: 159, icon: ContactsOutlined },
        { id: 160, icon: ContactsTwoTone },
        { id: 161, icon: ContainerFilled },
        { id: 162, icon: ContainerOutlined },
        { id: 163, icon: ContainerTwoTone },
        { id: 164, icon: ControlFilled },
        { id: 165, icon: ControlOutlined },
        { id: 166, icon: ControlTwoTone },
        { id: 167, icon: CopyFilled },
        { id: 168, icon: CopyOutlined },
        { id: 169, icon: CopyTwoTone },
        { id: 171, icon: CreditCardFilled },
        { id: 172, icon: CreditCardOutlined },
        { id: 173, icon: CreditCardTwoTone },
        { id: 174, icon: CrownFilled },
        { id: 175, icon: CrownOutlined },
        { id: 176, icon: CrownTwoTone },
        { id: 177, icon: CustomerServiceFilled },
        { id: 178, icon: CustomerServiceOutlined },
        { id: 179, icon: CustomerServiceTwoTone },
        { id: 180, icon: DashOutlined },
        { id: 181, icon: DashboardFilled },
        { id: 182, icon: DashboardOutlined },
        { id: 183, icon: DashboardTwoTone },
        { id: 184, icon: DatabaseFilled },
        { id: 185, icon: DatabaseOutlined },
        { id: 186, icon: DatabaseTwoTone },
        { id: 187, icon: DeleteColumnOutlined },
        { id: 188, icon: DeleteFilled },
        { id: 189, icon: DeleteOutlined },
        { id: 190, icon: DeleteRowOutlined },
        { id: 191, icon: DeleteTwoTone },
        { id: 192, icon: DeliveredProcedureOutlined },
        { id: 193, icon: DeploymentUnitOutlined },
        { id: 194, icon: DesktopOutlined },
        { id: 195, icon: DiffFilled },
        { id: 196, icon: DiffOutlined },
        { id: 197, icon: DiffTwoTone },
        { id: 198, icon: DingtalkCircleFilled },
        { id: 199, icon: DingtalkOutlined },
        { id: 200, icon: DingtalkSquareFilled },
        { id: 201, icon: DisconnectOutlined },
        { id: 202, icon: DislikeFilled },
        { id: 203, icon: DislikeOutlined },
        { id: 204, icon: DislikeTwoTone },
        { id: 205, icon: DollarCircleFilled },
        { id: 206, icon: DollarCircleOutlined },
        { id: 207, icon: DollarCircleTwoTone },
        { id: 208, icon: DollarOutlined },
        { id: 209, icon: DollarTwoTone },
        { id: 210, icon: DotChartOutlined },
        { id: 211, icon: DoubleLeftOutlined },
        { id: 212, icon: DoubleRightOutlined },
        { id: 213, icon: DownCircleFilled },
        { id: 214, icon: DownCircleOutlined },
        { id: 215, icon: DownCircleTwoTone },
        { id: 216, icon: DownOutlined },
        { id: 217, icon: DownSquareFilled },
        { id: 218, icon: DownSquareOutlined },
        { id: 219, icon: DownSquareTwoTone },
        { id: 220, icon: DownloadOutlined },
        { id: 221, icon: DragOutlined },
        { id: 222, icon: DribbbleCircleFilled },
        { id: 223, icon: DribbbleOutlined },
        { id: 224, icon: DribbbleSquareFilled },
        { id: 225, icon: DribbbleSquareOutlined },
        { id: 226, icon: DropboxCircleFilled },
        { id: 227, icon: DropboxOutlined },
        { id: 228, icon: DropboxSquareFilled },
        { id: 229, icon: EditFilled },
        { id: 230, icon: EditOutlined },
        { id: 231, icon: EditTwoTone },
        { id: 232, icon: EllipsisOutlined },
        { id: 233, icon: EnterOutlined },
        { id: 234, icon: EnvironmentFilled },
        { id: 235, icon: EnvironmentOutlined },
        { id: 236, icon: EnvironmentTwoTone },
        { id: 237, icon: EuroCircleFilled },
        { id: 238, icon: EuroCircleOutlined },
        { id: 239, icon: EuroCircleTwoTone },
        { id: 240, icon: EuroOutlined },
        { id: 241, icon: EuroTwoTone },
        { id: 242, icon: ExceptionOutlined },
        { id: 243, icon: ExclamationCircleFilled },
        { id: 244, icon: ExclamationCircleOutlined },
        { id: 245, icon: ExclamationCircleTwoTone },
        { id: 246, icon: ExclamationOutlined },
        { id: 247, icon: ExpandAltOutlined },
        { id: 248, icon: ExpandOutlined },
        { id: 249, icon: ExperimentFilled },
        { id: 250, icon: ExperimentOutlined },
        { id: 251, icon: ExperimentTwoTone },
        { id: 252, icon: ExportOutlined },
        { id: 253, icon: EyeFilled },
        { id: 254, icon: EyeInvisibleFilled },
        { id: 255, icon: EyeInvisibleOutlined },
        { id: 256, icon: EyeInvisibleTwoTone },
        { id: 257, icon: EyeOutlined },
        { id: 258, icon: EyeTwoTone },
        { id: 259, icon: FacebookFilled },
        { id: 260, icon: FacebookOutlined },
        { id: 261, icon: FallOutlined },
        { id: 262, icon: FastBackwardFilled },
        { id: 263, icon: FastBackwardOutlined },
        { id: 264, icon: FastForwardFilled },
        { id: 265, icon: FastForwardOutlined },
        { id: 266, icon: FieldBinaryOutlined },
        { id: 267, icon: FieldNumberOutlined },
        { id: 268, icon: FieldStringOutlined },
        { id: 269, icon: FieldTimeOutlined },
        { id: 270, icon: FileAddFilled },
        { id: 271, icon: FileAddOutlined },
        { id: 272, icon: FileAddTwoTone },
        { id: 273, icon: FileDoneOutlined },
        { id: 274, icon: FileExcelFilled },
        { id: 275, icon: FileExcelOutlined },
        { id: 276, icon: FileExcelTwoTone },
        { id: 277, icon: FileExclamationFilled },
        { id: 278, icon: FileExclamationOutlined },
        { id: 279, icon: FileExclamationTwoTone },
        { id: 280, icon: FileFilled },
        { id: 281, icon: FileGifOutlined },
        { id: 282, icon: FileImageFilled },
        { id: 283, icon: FileImageOutlined },
        { id: 284, icon: FileImageTwoTone },
        { id: 285, icon: FileJpgOutlined },
        { id: 286, icon: FileMarkdownFilled },
        { id: 287, icon: FileMarkdownOutlined },
        { id: 288, icon: FileMarkdownTwoTone },
        { id: 289, icon: FileOutlined },
        { id: 290, icon: FilePdfFilled },
        { id: 291, icon: FilePdfOutlined },
        { id: 292, icon: FilePdfTwoTone },
        { id: 293, icon: FilePptFilled },
        { id: 294, icon: FilePptOutlined },
        { id: 295, icon: FilePptTwoTone },
        { id: 296, icon: FileProtectOutlined },
        { id: 297, icon: FileSearchOutlined },
        { id: 298, icon: FileSyncOutlined },
        { id: 299, icon: FileTextFilled },
        { id: 300, icon: FileTextOutlined },
        { id: 301, icon: FileTextTwoTone },
        { id: 302, icon: FileTwoTone },
        { id: 303, icon: FileUnknownFilled },
        { id: 304, icon: FileUnknownOutlined },
        { id: 305, icon: FileUnknownTwoTone },
        { id: 306, icon: FileWordFilled },
        { id: 307, icon: FileWordOutlined },
        { id: 308, icon: FileWordTwoTone },
        { id: 309, icon: FileZipFilled },
        { id: 310, icon: FileZipOutlined },
        { id: 311, icon: FileZipTwoTone },
        { id: 312, icon: FilterFilled },
        { id: 313, icon: FilterOutlined },
        { id: 314, icon: FilterTwoTone },
        { id: 315, icon: FireFilled },
        { id: 316, icon: FireOutlined },
        { id: 317, icon: FireTwoTone },
        { id: 318, icon: FlagFilled },
        { id: 319, icon: FlagOutlined },
        { id: 320, icon: FlagTwoTone },
        { id: 321, icon: FolderAddFilled },
        { id: 322, icon: FolderAddOutlined },
        { id: 323, icon: FolderAddTwoTone },
        { id: 324, icon: FolderFilled },
        { id: 325, icon: FolderOpenFilled },
        { id: 326, icon: FolderOpenOutlined },
        { id: 327, icon: FolderOpenTwoTone },
        { id: 328, icon: FolderOutlined },
        { id: 329, icon: FolderTwoTone },
        { id: 330, icon: FolderViewOutlined },
        { id: 331, icon: FontColorsOutlined },
        { id: 332, icon: FontSizeOutlined },
        { id: 333, icon: ForkOutlined },
        { id: 334, icon: FormOutlined },
        { id: 335, icon: FormatPainterFilled },
        { id: 336, icon: FormatPainterOutlined },
        { id: 337, icon: ForwardFilled },
        { id: 338, icon: ForwardOutlined },
        { id: 339, icon: FrownFilled },
        { id: 340, icon: FrownOutlined },
        { id: 341, icon: FrownTwoTone },
        { id: 342, icon: FullscreenExitOutlined },
        { id: 343, icon: FullscreenOutlined },
        { id: 344, icon: FunctionOutlined },
        { id: 345, icon: FundFilled },
        { id: 346, icon: FundOutlined },
        { id: 347, icon: FundProjectionScreenOutlined },
        { id: 348, icon: FundTwoTone },
        { id: 349, icon: FundViewOutlined },
        { id: 350, icon: FunnelPlotFilled },
        { id: 351, icon: FunnelPlotOutlined },
        { id: 352, icon: FunnelPlotTwoTone },
        { id: 353, icon: GatewayOutlined },
        { id: 354, icon: GifOutlined },
        { id: 355, icon: GiftFilled },
        { id: 356, icon: GiftOutlined },
        { id: 357, icon: GiftTwoTone },
        { id: 358, icon: GithubFilled },
        { id: 359, icon: GithubOutlined },
        { id: 360, icon: GitlabFilled },
        { id: 361, icon: GitlabOutlined },
        { id: 362, icon: GlobalOutlined },
        { id: 363, icon: GoldFilled },
        { id: 364, icon: GoldOutlined },
        { id: 365, icon: GoldTwoTone },
        { id: 366, icon: GoogleCircleFilled },
        { id: 367, icon: GoogleOutlined },
        { id: 368, icon: GooglePlusCircleFilled },
        { id: 369, icon: GooglePlusOutlined },
        { id: 370, icon: GooglePlusSquareFilled },
        { id: 371, icon: GoogleSquareFilled },
        { id: 372, icon: GroupOutlined },
        { id: 373, icon: HddFilled },
        { id: 374, icon: HddOutlined },
        { id: 375, icon: HddTwoTone },
        { id: 376, icon: HeartFilled },
        { id: 377, icon: HeartOutlined },
        { id: 378, icon: HeartTwoTone },
        { id: 379, icon: HeatMapOutlined },
        { id: 380, icon: HighlightFilled },
        { id: 381, icon: HighlightOutlined },
        { id: 382, icon: HighlightTwoTone },
        { id: 383, icon: HistoryOutlined },
        { id: 384, icon: HomeFilled },
        { id: 385, icon: HomeOutlined },
        { id: 386, icon: HomeTwoTone },
        { id: 387, icon: HourglassFilled },
        { id: 388, icon: HourglassOutlined },
        { id: 389, icon: HourglassTwoTone },
        { id: 390, icon: Html5Filled },
        { id: 391, icon: Html5Outlined },
        { id: 392, icon: Html5TwoTone },
        { id: 393, icon: IdcardFilled },
        { id: 394, icon: IdcardOutlined },
        { id: 395, icon: IdcardTwoTone },
        { id: 396, icon: IeCircleFilled },
        { id: 397, icon: IeOutlined },
        { id: 398, icon: IeSquareFilled },
        { id: 399, icon: ImportOutlined },
        { id: 400, icon: InboxOutlined },
        { id: 401, icon: InfoCircleFilled },
        { id: 402, icon: InfoCircleOutlined },
        { id: 403, icon: InfoCircleTwoTone },
        { id: 404, icon: InfoOutlined },
        { id: 405, icon: InsertRowAboveOutlined },
        { id: 406, icon: InsertRowBelowOutlined },
        { id: 407, icon: InsertRowLeftOutlined },
        { id: 408, icon: InsertRowRightOutlined },
        { id: 409, icon: InstagramFilled },
        { id: 410, icon: InstagramOutlined },
        { id: 411, icon: InsuranceFilled },
        { id: 412, icon: InsuranceOutlined },
        { id: 413, icon: InsuranceTwoTone },
        { id: 414, icon: InteractionFilled },
        { id: 415, icon: InteractionOutlined },
        { id: 416, icon: InteractionTwoTone },
        { id: 417, icon: IssuesCloseOutlined },
        { id: 418, icon: ItalicOutlined },
        { id: 419, icon: KeyOutlined },
        { id: 420, icon: LaptopOutlined },
        { id: 421, icon: LayoutFilled },
        { id: 422, icon: LayoutOutlined },
        { id: 423, icon: LayoutTwoTone },
        { id: 424, icon: LeftCircleFilled },
        { id: 425, icon: LeftCircleOutlined },
        { id: 426, icon: LeftCircleTwoTone },
        { id: 427, icon: LeftOutlined },
        { id: 428, icon: LeftSquareFilled },
        { id: 429, icon: LeftSquareOutlined },
        { id: 430, icon: LeftSquareTwoTone },
        { id: 431, icon: LikeFilled },
        { id: 432, icon: LikeOutlined },
        { id: 433, icon: LikeTwoTone },
        { id: 434, icon: LineChartOutlined },
        { id: 435, icon: LineHeightOutlined },
        { id: 436, icon: LineOutlined },
        { id: 437, icon: LinkOutlined },
        { id: 438, icon: LinkedinFilled },
        { id: 439, icon: LinkedinOutlined },
        { id: 440, icon: Loading3QuartersOutlined },
        { id: 441, icon: LoadingOutlined },
        { id: 442, icon: LockFilled },
        { id: 443, icon: LockOutlined },
        { id: 444, icon: LockTwoTone },
        { id: 445, icon: LoginOutlined },
        { id: 446, icon: LogoutOutlined },
        { id: 447, icon: MacCommandFilled },
        { id: 448, icon: MacCommandOutlined },
        { id: 449, icon: MailFilled },
        { id: 450, icon: MailOutlined },
        { id: 451, icon: MailTwoTone },
        { id: 452, icon: ManOutlined },
        { id: 453, icon: MedicineBoxFilled },
        { id: 454, icon: MedicineBoxOutlined },
        { id: 455, icon: MedicineBoxTwoTone },
        { id: 456, icon: MediumCircleFilled },
        { id: 457, icon: MediumOutlined },
        { id: 458, icon: MediumSquareFilled },
        { id: 459, icon: MediumWorkmarkOutlined },
        { id: 460, icon: MehFilled },
        { id: 461, icon: MehOutlined },
        { id: 462, icon: MehTwoTone },
        { id: 463, icon: MenuFoldOutlined },
        { id: 464, icon: MenuOutlined },
        { id: 465, icon: MenuUnfoldOutlined },
        { id: 466, icon: MergeCellsOutlined },
        { id: 467, icon: MessageFilled },
        { id: 468, icon: MessageOutlined },
        { id: 469, icon: MessageTwoTone },
        { id: 470, icon: MinusCircleFilled },
        { id: 471, icon: MinusCircleOutlined },
        { id: 472, icon: MinusCircleTwoTone },
        { id: 473, icon: MinusOutlined },
        { id: 474, icon: MinusSquareFilled },
        { id: 475, icon: MinusSquareOutlined },
        { id: 476, icon: MinusSquareTwoTone },
        { id: 477, icon: MobileFilled },
        { id: 478, icon: MobileOutlined },
        { id: 479, icon: MobileTwoTone },
        { id: 480, icon: MoneyCollectFilled },
        { id: 481, icon: MoneyCollectOutlined },
        { id: 482, icon: MoneyCollectTwoTone },
        { id: 483, icon: MonitorOutlined },
        { id: 484, icon: MoreOutlined },
        { id: 485, icon: NodeCollapseOutlined },
        { id: 486, icon: NodeExpandOutlined },
        { id: 487, icon: NodeIndexOutlined },
        { id: 488, icon: NotificationFilled },
        { id: 489, icon: NotificationOutlined },
        { id: 490, icon: NotificationTwoTone },
        { id: 491, icon: NumberOutlined },
        { id: 492, icon: OneToOneOutlined },
        { id: 493, icon: OrderedListOutlined },
        { id: 494, icon: PaperClipOutlined },
        { id: 495, icon: PartitionOutlined },
        { id: 496, icon: PauseCircleFilled },
        { id: 497, icon: PauseCircleOutlined },
        { id: 498, icon: PauseCircleTwoTone },
        { id: 499, icon: PauseOutlined },
        { id: 500, icon: PayCircleFilled },
        { id: 501, icon: PayCircleOutlined },
        { id: 502, icon: PercentageOutlined },
        { id: 503, icon: PhoneFilled },
        { id: 504, icon: PhoneOutlined },
        { id: 505, icon: PhoneTwoTone },
        { id: 506, icon: PicCenterOutlined },
        { id: 507, icon: PicLeftOutlined },
        { id: 508, icon: PicRightOutlined },
        { id: 509, icon: PictureFilled },
        { id: 510, icon: PictureOutlined },
        { id: 511, icon: PictureTwoTone },
        { id: 512, icon: PieChartFilled },
        { id: 513, icon: PieChartOutlined },
        { id: 514, icon: PieChartTwoTone },
        { id: 515, icon: PlayCircleFilled },
        { id: 516, icon: PlayCircleOutlined },
        { id: 517, icon: PlayCircleTwoTone },
        { id: 518, icon: PlaySquareFilled },
        { id: 519, icon: PlaySquareOutlined },
        { id: 520, icon: PlaySquareTwoTone },
        { id: 521, icon: PlusCircleFilled },
        { id: 522, icon: PlusCircleOutlined },
        { id: 523, icon: PlusCircleTwoTone },
        { id: 524, icon: PlusOutlined },
        { id: 525, icon: PlusSquareFilled },
        { id: 526, icon: PlusSquareOutlined },
        { id: 527, icon: PlusSquareTwoTone },
        { id: 528, icon: PoundCircleFilled },
        { id: 529, icon: PoundCircleOutlined },
        { id: 530, icon: PoundCircleTwoTone },
        { id: 531, icon: PoundOutlined },
        { id: 532, icon: PoweroffOutlined },
        { id: 533, icon: PrinterFilled },
        { id: 534, icon: PrinterOutlined },
        { id: 535, icon: PrinterTwoTone },
        { id: 536, icon: ProfileFilled },
        { id: 537, icon: ProfileOutlined },
        { id: 538, icon: ProfileTwoTone },
        { id: 539, icon: ProjectFilled },
        { id: 540, icon: ProjectOutlined },
        { id: 541, icon: ProjectTwoTone },
        { id: 542, icon: PropertySafetyFilled },
        { id: 543, icon: PropertySafetyOutlined },
        { id: 544, icon: PropertySafetyTwoTone },
        { id: 545, icon: PullRequestOutlined },
        { id: 546, icon: PushpinFilled },
        { id: 547, icon: PushpinOutlined },
        { id: 548, icon: PushpinTwoTone },
        { id: 549, icon: QqCircleFilled },
        { id: 550, icon: QqOutlined },
        { id: 551, icon: QqSquareFilled },
        { id: 552, icon: QrcodeOutlined },
        { id: 553, icon: QuestionCircleFilled },
        { id: 554, icon: QuestionCircleOutlined },
        { id: 555, icon: QuestionCircleTwoTone },
        { id: 556, icon: QuestionOutlined },
        { id: 557, icon: RadarChartOutlined },
        { id: 558, icon: RadiusBottomleftOutlined },
        { id: 559, icon: RadiusBottomrightOutlined },
        { id: 560, icon: RadiusSettingOutlined },
        { id: 561, icon: RadiusUpleftOutlined },
        { id: 562, icon: RadiusUprightOutlined },
        { id: 563, icon: ReadFilled },
        { id: 564, icon: ReadOutlined },
        { id: 565, icon: ReconciliationFilled },
        { id: 566, icon: ReconciliationOutlined },
        { id: 567, icon: ReconciliationTwoTone },
        { id: 568, icon: RedEnvelopeFilled },
        { id: 569, icon: RedEnvelopeOutlined },
        { id: 570, icon: RedEnvelopeTwoTone },
        { id: 571, icon: RedditCircleFilled },
        { id: 572, icon: RedditOutlined },
        { id: 573, icon: RedditSquareFilled },
        { id: 574, icon: RedoOutlined },
        { id: 575, icon: ReloadOutlined },
        { id: 576, icon: RestFilled },
        { id: 577, icon: RestOutlined },
        { id: 578, icon: RestTwoTone },
        { id: 579, icon: RetweetOutlined },
        { id: 580, icon: RightCircleFilled },
        { id: 581, icon: RightCircleOutlined },
        { id: 582, icon: RightCircleTwoTone },
        { id: 583, icon: RightOutlined },
        { id: 584, icon: RightSquareFilled },
        { id: 585, icon: RightSquareOutlined },
        { id: 586, icon: RightSquareTwoTone },
        { id: 587, icon: RiseOutlined },
        { id: 588, icon: RobotFilled },
        { id: 589, icon: RobotOutlined },
        { id: 590, icon: RocketFilled },
        { id: 591, icon: RocketOutlined },
        { id: 592, icon: RocketTwoTone },
        { id: 593, icon: RollbackOutlined },
        { id: 594, icon: RotateLeftOutlined },
        { id: 595, icon: RotateRightOutlined },
        { id: 596, icon: SafetyCertificateFilled },
        { id: 597, icon: SafetyCertificateOutlined },
        { id: 598, icon: SafetyCertificateTwoTone },
        { id: 599, icon: SafetyOutlined },
        { id: 600, icon: SaveFilled },
        { id: 601, icon: SaveOutlined },
        { id: 602, icon: SaveTwoTone },
        { id: 603, icon: ScanOutlined },
        { id: 604, icon: ScheduleFilled },
        { id: 605, icon: ScheduleOutlined },
        { id: 606, icon: ScheduleTwoTone },
        { id: 607, icon: ScissorOutlined },
        { id: 608, icon: SearchOutlined },
        { id: 609, icon: SecurityScanFilled },
        { id: 610, icon: SecurityScanOutlined },
        { id: 611, icon: SecurityScanTwoTone },
        { id: 612, icon: SelectOutlined },
        { id: 613, icon: SendOutlined },
        { id: 614, icon: SettingFilled },
        { id: 615, icon: SettingOutlined },
        { id: 616, icon: SettingTwoTone },
        { id: 617, icon: ShakeOutlined },
        { id: 618, icon: ShareAltOutlined },
        { id: 619, icon: ShoppingCartOutlined },
        { id: 620, icon: ShopFilled },
        { id: 621, icon: ShopOutlined },
        { id: 622, icon: ShopTwoTone },
        { id: 623, icon: ShoppingCartOutlined },
        { id: 624, icon: ShoppingFilled },
        { id: 625, icon: ShoppingOutlined },
        { id: 626, icon: ShoppingTwoTone },
        { id: 627, icon: ShrinkOutlined },
        { id: 628, icon: SignalFilled },
        { id: 629, icon: SisternodeOutlined },
        { id: 630, icon: SketchCircleFilled },
        { id: 631, icon: SketchOutlined },
        { id: 632, icon: SketchSquareFilled },
        { id: 633, icon: SkinFilled },
        { id: 634, icon: SkinOutlined },
        { id: 635, icon: SkinTwoTone },
        { id: 636, icon: SkypeFilled },
        { id: 637, icon: SkypeOutlined },
        { id: 638, icon: SlackCircleFilled },
        { id: 639, icon: SlackOutlined },
        { id: 640, icon: SlackSquareFilled },
        { id: 641, icon: SlackSquareOutlined },
        { id: 642, icon: SlidersFilled },
        { id: 643, icon: SlidersOutlined },
        { id: 644, icon: SlidersTwoTone },
        { id: 645, icon: SmallDashOutlined },
        { id: 646, icon: SmileFilled },
        { id: 647, icon: SmileOutlined },
        { id: 648, icon: SmileTwoTone },
        { id: 649, icon: SnippetsFilled },
        { id: 650, icon: SnippetsOutlined },
        { id: 651, icon: SnippetsTwoTone },
        { id: 652, icon: SolutionOutlined },
        { id: 653, icon: SortAscendingOutlined },
        { id: 654, icon: SortDescendingOutlined },
        { id: 655, icon: SoundFilled },
        { id: 656, icon: SoundOutlined },
        { id: 657, icon: SoundTwoTone },
        { id: 658, icon: SplitCellsOutlined },
        { id: 659, icon: StarFilled },
        { id: 660, icon: StarOutlined },
        { id: 661, icon: StarTwoTone },
        { id: 662, icon: StepBackwardFilled },
        { id: 663, icon: StepBackwardOutlined },
        { id: 664, icon: StepForwardFilled },
        { id: 665, icon: StepForwardOutlined },
        { id: 666, icon: StockOutlined },
        { id: 667, icon: StopFilled },
        { id: 668, icon: StopOutlined },
        { id: 669, icon: StopTwoTone },
        { id: 670, icon: StrikethroughOutlined },
        { id: 671, icon: SubnodeOutlined },
        { id: 672, icon: SwapLeftOutlined },
        { id: 673, icon: SwapOutlined },
        { id: 674, icon: SwapRightOutlined },
        { id: 675, icon: SwitcherFilled },
        { id: 676, icon: SwitcherOutlined },
        { id: 677, icon: SwitcherTwoTone },
        { id: 678, icon: SyncOutlined },
        { id: 679, icon: TableOutlined },
        { id: 680, icon: TabletFilled },
        { id: 681, icon: TabletOutlined },
        { id: 682, icon: TabletTwoTone },
        { id: 683, icon: TagFilled },
        { id: 684, icon: TagOutlined },
        { id: 685, icon: TagTwoTone },
        { id: 686, icon: TagsFilled },
        { id: 687, icon: TagsOutlined },
        { id: 688, icon: TagsTwoTone },
        { id: 689, icon: TaobaoCircleFilled },
        { id: 690, icon: TaobaoCircleOutlined },
        { id: 691, icon: TaobaoOutlined },
        { id: 692, icon: TaobaoSquareFilled },
        { id: 693, icon: TeamOutlined },
        { id: 694, icon: ThunderboltFilled },
        { id: 695, icon: ThunderboltOutlined },
        { id: 696, icon: ThunderboltTwoTone },
        { id: 697, icon: ToTopOutlined },
        { id: 698, icon: ToolFilled },
        { id: 699, icon: ToolOutlined },
        { id: 700, icon: ToolTwoTone },
        { id: 701, icon: TrademarkCircleFilled },
        { id: 702, icon: TrademarkCircleOutlined },
        { id: 703, icon: TrademarkCircleTwoTone },
        { id: 704, icon: TrademarkOutlined },
        { id: 705, icon: TransactionOutlined },
        { id: 706, icon: TranslationOutlined },
        { id: 707, icon: TrophyFilled },
        { id: 708, icon: TrophyOutlined },
        { id: 709, icon: TrophyTwoTone },
        { id: 710, icon: TwitterCircleFilled },
        { id: 711, icon: TwitterOutlined },
        { id: 712, icon: TwitterSquareFilled },
        { id: 713, icon: UnderlineOutlined },
        { id: 714, icon: UndoOutlined },
        { id: 715, icon: UngroupOutlined },
        { id: 716, icon: UnlockFilled },
        { id: 717, icon: UnlockOutlined },
        { id: 718, icon: UnlockTwoTone },
        { id: 719, icon: UnorderedListOutlined },
        { id: 720, icon: UpCircleFilled },
        { id: 721, icon: UpCircleOutlined },
        { id: 722, icon: UpCircleTwoTone },
        { id: 723, icon: UpOutlined },
        { id: 724, icon: UpSquareFilled },
        { id: 725, icon: UpSquareOutlined },
        { id: 726, icon: UpSquareTwoTone },
        { id: 727, icon: UploadOutlined },
        { id: 728, icon: UsbFilled },
        { id: 729, icon: UsbOutlined },
        { id: 730, icon: UsbTwoTone },
        { id: 731, icon: UserAddOutlined },
        { id: 732, icon: UserDeleteOutlined },
        { id: 733, icon: UserOutlined },
        { id: 734, icon: UserSwitchOutlined },
        { id: 735, icon: UsergroupAddOutlined },
        { id: 736, icon: UsergroupDeleteOutlined },
        { id: 737, icon: VerifiedOutlined },
        { id: 738, icon: VerticalAlignBottomOutlined },
        { id: 739, icon: VerticalAlignMiddleOutlined },
        { id: 740, icon: VerticalAlignTopOutlined },
        { id: 741, icon: VerticalLeftOutlined },
        { id: 742, icon: VerticalRightOutlined },
        { id: 743, icon: VideoCameraAddOutlined },
        { id: 744, icon: VideoCameraFilled },
        { id: 745, icon: VideoCameraOutlined },
        { id: 746, icon: VideoCameraTwoTone },
        { id: 747, icon: WalletFilled },
        { id: 748, icon: WalletOutlined },
        { id: 749, icon: WalletTwoTone },
        { id: 750, icon: WarningFilled },
        { id: 751, icon: WarningOutlined },
        { id: 752, icon: WarningTwoTone },
        { id: 753, icon: WechatFilled },
        { id: 754, icon: WechatOutlined },
        { id: 755, icon: WeiboCircleFilled },
        { id: 756, icon: WeiboCircleOutlined },
        { id: 757, icon: WeiboOutlined },
        { id: 758, icon: WeiboSquareFilled },
        { id: 759, icon: WhatsAppOutlined },
        { id: 760, icon: WifiOutlined },
        { id: 761, icon: WindowsFilled },
        { id: 762, icon: WindowsOutlined },
        { id: 763, icon: WomanOutlined },
        { id: 764, icon: YahooFilled },
        { id: 765, icon: YahooOutlined },
        { id: 766, icon: YoutubeFilled },
        { id: 767, icon: YoutubeOutlined },
        { id: 768, icon: YuqueFilled },
        { id: 769, icon: YuqueOutlined },
        { id: 770, icon: ZhihuCircleFilled },
        { id: 771, icon: ZhihuOutlined },
        { id: 772, icon: ZhihuSquareFilled },
        { id: 773, icon: CaretDownFilled },
        { id: 774, icon: CaretDownOutlined },
        { id: 776, icon: CaretLeftFilled },
        { id: 777, icon: CaretLeftOutlined },
        { id: 779, icon: CaretRightFilled },
        { id: 780, icon: CaretRightOutlined },
        { id: 782, icon: DingdingOutlined },
        { id: 783, icon: CaretUpFilled },
        { id: 784, icon: CaretUpOutlined },
        { id: 785, icon: GoldenFilled },

        
    ];
    
    const styles = {
        iconsWrapper: {
            display: "flex",
            flexWrap: "wrap",
            padding: "20px 30px",
        },
        icon: {
            marginTop: "3px",
            fontSize: "25px",
        },
        iconLabel: {
            marginLeft: "10px",
            fontSize: "17px",
        },
        iconConatainer: {
            marginRight: "15px",
            marginTop: "10px",
            display: "flex",
        },
    };

    // function getIconName(icon) {
    //     const componentName = icon.type.displayName || icon.type.name || '';
    //     const iconName = componentName.replace(/Filled$|Outlined$|TwoTone$/, '');
    //     return iconName.replace(/([a-z])([A-Z])/g, '$1 $2');
    //   }
    return (
        <div className="iconsWrapper" style={styles.iconsWrapper}>
            {Icons.map(({ id, icon: Icon }) => (
                <div className="iconContainer" style={styles.iconConatainer}>
                        <Icon className="icon" style={styles.icon}/>
                        <label className="iconLabel" style={styles.iconLabel} ><p></p></label>
                </div>
            ))}
        </div>
    );
};
