spring:
  datasource:
    url: jdbc:postgresql://google/bba?cloudSqlInstance=noble-airport-411617:us-west1:bba-database-server&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  hikari:
    data-source-properties:
      SocketFactory: com.google.cloud.sql.postgres.SocketFactory
      cloudSqlInstance: noble-airport-411617:us-west1:bba-database-server
  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG