spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bba
    username: postgres
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS

  mail:
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
    host: smtp.gmail.com
    port: 587
    username: nagarajukasarla79@gmail.com
    password: duarabbmislklnjn

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG